### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by mikemorris**
Content sourced from https://www.hashicorp.com/security#vulnerability-reporting

### CODE REVIEW

**Review by hanshasselberg — DISMISSED** [review]
LGTM

**Comment by chair6** [comment]
Just a quick note on this, we've got a WIP-RFC that covers this among a number of other external-facing security things.  Will be addressed soon!

**Comment by chair6** [comment]
Relevant RFC is at https://docs.google.com/document/d/15QALzkwwpjRCM7zX0o-P2P9OZEgpOuABgaP3qUc2_OU/.

**Review by briancain — APPROVED** [review]
:closed_lock_with_key: :heavy_check_mark:

**Review by hanshasselberg — APPROVED** [review]
Lgtm

**Comment by iSystem32** [comment]
> Content sourced from https://www.hashicorp.com/security#vulnerability-reporting

[]()

**Pull request merged**
